[tool.poetry]
name = "kalshi-bot"
version = "0.1.0"
description = ""
authors = ["kamyarghiam <kamyarghiam@gmail.com>"]
readme = "README.md"
packages = [{include = "kalshi_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
