[project]
name = "Kalshi Bot"
# NOTE: to change python version, don't forget to change it in
# the pre-commit-config.yaml as well
requires-python = ">=3.11.2"

[tool.poetry]
name = "kalshi-bot"
version = "0.1.0"
description = ""
authors = ["kamyarghiam <kamyarghiam@gmail.com>"]
readme = "README.md"
packages = [{include = "kalshi_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.2.2"
pathlib = "^1.0.1"
pydantic = "^1.10.7"
mock = "^5.0.1"
requests = "^2.28.2"
fastapi = "^0.95.0"
httpx = "^0.23.3"
types-mock = "^5.0.0.5"
types-requests = "^2.28.11.16"
mypy = "^1.1.1"
pytest-cov = "^4.0.0"
websocket-client = "^1.5.1"
polyfactory = "^2.0.0a1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
