from src.helpers.types.url import URL

KALSHI_PROD_BASE_URL = "trading-api.kalshi.com"

# URL's
EXCHANGE_STATUS_URL = URL("exchange/status")
LOGIN_URL = URL("login/")

# Env vars
USERNAME_ENV_VAR = "API_USERNAME"
PASSWORD_ENV_VAR = "API_PASSWORD"
URL_ENV_VAR = "API_URL"
API_VERSION_ENV_VAR = "API_VERSION"
ENV_VARS = [
    USERNAME_ENV_VAR,
    PASSWORD_ENV_VAR,
    URL_ENV_VAR,
    API_VERSION_ENV_VAR,
]
